### ISSUE TITLE
GHC 9.2 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#148]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 9.2:

* [x] Adapt to [type applications in patterns](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/2464)
* [x] Adapt to `OverloadedRecordDot`
* [x] Figure out what to do with #151
* [x] Fix an `-Wincomplete-record-updates` warning in `Test.Run`:

  ```
  [6 of 6] Compiling Main             ( Test/Run.hs, /home/ryanglscott/Documents/Hacking/Haskell/ci-maintenance/checkout/goldfirere/th-desugar/dist-newstyle/build/x86_64-linux/ghc-9.1.20210322/th-desugar-1.13/t/spec/build/spec/spec-tmp/Main.o, /home/ryanglscott/Documents/Hacking/Haskell/ci-maintenance/checkout/goldfirere/th-desugar/dist-newstyle/build/x86_64-linux/ghc-9.1.20210322/th-desugar-1.13/t/spec/build/spec/spec-tmp/Main.dyn_o )
  
  Test/Run.hs:98:31: warning: [-Wincomplete-record-updates]
      Pattern match(es) are non-exhaustive
      In a record-update construct:
          Patterns of type ‘Record’ not matched: MkRecord2 _ _
     |
  98 |              , "record"   ~: $test14_record   @=? $(dsSplice test14_record)
     |                               ^^^^^^^^^^^^^
  ```

  (**EDIT**: Worked around in 4b02b029ef9699c4bef012441a406f7993874355.)

**Comment by RyanGlScott** [comment]
[`th-desguar-1.13`](https://hackage.haskell.org/package/th-desugar-1.13)

**Comment by expipiplus1** [comment]
Thanks, @RyanGlScott!
