### ISSUE TITLE
GHC 9.10 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#191]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 9.10:

* [x] https://github.com/goldfirere/th-desugar/issues/202
* [x] https://github.com/goldfirere/th-desugar/issues/203
* [x] https://github.com/goldfirere/th-desugar/pull/211
* [x] https://github.com/goldfirere/th-desugar/pull/212
* [x] https://github.com/goldfirere/th-desugar/pull/213
* [x] Hackage release

**Comment by RyanGlScott** [comment]
[`th-desugar-1.17`](https://hackage.haskell.org/package/th-desugar-1.17)
