### ISSUE TITLE
GHC 8.8 checklist

### ISSUE THREAD

**Issue by RyanGlScott** [goldfirere/th-desugar#90]
This issue serves as a reminder to do certain things before we ship a new major release that supports GHC 8.8:

* [ ] Update `th-desugar` to handle `ImplicitParams` and `RecursiveDo` (see [this GHC commit](http://git.haskell.org/ghc.git/commit/9c6b7493db24977595b17046e15baf76638b5317)).
* [ ] Update `th-desugar` to handle the [More explicit foralls](http://git.haskell.org/ghc.git/commit/512eeb9bb9a81e915bfab25ca16bc87c62252064) proposal.
* [ ] Update `th-desugar` to accommodate visible kind applications.

**Comment by RyanGlScott** [comment]
While designing a patch to accomplish this, I ran into some design questions:

* Due to the More visible foralls proposal, several AST forms now have a `Maybe [TyVarBndr]` field to represent the explicit foralls (if they exist). Should we copy this design for `th-desugar` (i.e., use `Maybe [DTyVarBndr]`), or would it make more sense to always quantify the type variables (i.e., use `[DTyVarBndr]`)?
* Template Haskell now supports recursive-`do` notation, but `th-desugar` has no notion of a `Stmt`. For instance, `do`-notation is currently desugared to uses of `(>>=)`, so there is no need for something like `DStmt` at present. However, the desugaring of recursive `do`-notation is much, much more complicated. Do we want to try to mimic this desugaring in `th-desugar`?

**Comment by goldfirere** [comment]
I think we should stick with `[DTyVarBndr]`. What this means, in practice, is that we'll have to gather any out-of-scope type variables and put them in the `[DTyVarBndr]`. (I forget if we already do that.) If this turns out to be prohibitively hard, I can change my mind.

I'm agnostic on the recursive-`do` part. For instance, I'd be happy just failing on recursive 'do's. If we do support it, though, I think we should implement the complicated desugaring, as long as that desugaring is fully faithful.

**Comment by goldfirere** [comment]
I think (1) is the only viable option here, because (I believe) users can (ill-advisedly) bind a type variable of the same name in an instance declaration, and there'd be no way to distinguish between this silly user behavior and the added binders from an unmodified `dsDec`. So: this seems sad, but necessary.
